# Practice Test (Blank) — NumPy & Pandas

**Topics:** NumPy (numerical analysis, probability) • Pandas (Series, DataFrame)

Solve each question in the empty cell below it. Try **without** looking at notes first.
Answer key is in `practice-test.md` if you get stuck.

Run this first to import everything:

In [1]:
import numpy as np
import pandas as pd

## Section A — NumPy: Numerical Analysis

**A1.** Create a NumPy array of the numbers 10 to 50 (inclusive) and print its `shape`, `size`, `ndim`, and `dtype`.

In [5]:
a = np.arange(10 , 51)
print(f"shape: {a.shape}\nsize: {a.size}\nndim: {a.ndim}\ndtype: {a.dtype}")

shape: (40,)
size: 40
ndim: 1
dtype: int64


**A2.** Given `a = np.array([4, 8, 15, 16, 23, 42])`, compute the **sum**, **mean**, **median**, **standard deviation**, and **variance**.

In [6]:
a = np.array([4, 8, 15, 16, 23, 42])
print(f"sum: {np.sum(a)}\nmean: {np.mean(a)}\nmedian: {np.median(a)}\nstandard deviation: {np.std(a)}\nvariance: {np.var(a)}")

sum: 108
mean: 18.0
median: 15.5
standard deviation: 12.315302134607444
variance: 151.66666666666666


**A3.** For a `(3, 4)` array `m = np.arange(12).reshape(3, 4)`, compute `np.sum(m, axis=0)` and `np.sum(m, axis=1)`. What is the output shape of each?

In [12]:
m = np.arange(12).reshape(3, 4)
np.sum(m, axis=0) # will give the sum of each column
np.sum(m, axis=1) # will give the sum of each row

array([ 6, 22, 38])

**A4.** Given `arr = np.array([3, 1, 7, 2, 9, 4])`, find: (a) index of the max, (b) index of the min, (c) the array sorted ascending.

In [14]:
arr = np.array([3, 1, 7, 2, 9, 4])
print(f"(a) Index of the max {np.argmax(arr)}")
print(f"(b) Index of the min {np.argmin(arr)}")
print(f"(c) The array sorted ascending {np.sort(arr)}")


(a) Index of the max 4
(b) Index of the min 1
(c) The array sorted ascending [1 2 3 4 7 9]


**A5.** Use `np.cumsum` and `np.diff` on `np.array([2, 5, 9, 14])`. Why does `diff` return one fewer element?

In [19]:
arr = np.array([2, 5, 9, 14])
print(arr)
print(np.cumsum(arr))
print(np.diff(arr)) # will give one fewer element because it takes 2 adjacent elements.

[ 2  5  9 14]
[ 2  7 16 30]
[3 4 5]


**A6.** Reshape `np.arange(12)` into a `(3, 4)` matrix, then compute the **mean of each column** and the **max of each row**.

In [23]:
arr = np.arange(12)
r_arr = np.reshape(arr, (3,4))
print(r_arr)
print(f"Mean of each column: {np.mean(r_arr, axis=0)}\nMax of each row: {np.max(r_arr, axis=1)}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mean of each column: [4. 5. 6. 7.]
Max of each column: [ 8  9 10 11]


**A7.** From `data = np.array([12, 7, 22, 3, 18, 9])`, use **boolean masking** to (a) select all values > 10, and (b) count how many values are even.

In [36]:
data = np.array([12, 7, 22, 3, 18, 9])
gr_10 = data[data > 10]
evens = np.sum(data % 2 == 0)
print(f"Values greater than 10: {gr_10}\nTotal even values: {evens}")

Values greater than 10: [12 22 18]
Total even values: 3


**A8.** Show broadcasting: compute `np.array([1, 2, 3]) * 10` and `np.array([[1],[2],[3]]) + np.array([10, 20, 30])`. Explain the second result's shape.

In [43]:
arr = np.array([1, 2, 3]) * 10
arr_2 = np.array([[1],[2],[3]]) + np.array([10, 20, 30])
print(arr_2,arr_2.shape)

[[11 21 31]
 [12 22 32]
 [13 23 33]] (3, 3)


**A9.** Create a 3×3 identity matrix and a 3×3 matrix of all sevens without typing the numbers manually.

In [50]:
arr = np.eye(3)
constant_matrix = np.full((3, 3), 7)
print("3x3 identity matrix:\n", arr)
print("\n3x3 matrix of sevens:\n", constant_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x3 matrix of sevens:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


**A10.** Given `s = np.array([120, 90, 200, 175, 60, 145])`, compute the **total**, the **average**, and the **percentage each month** contributes to the total.

In [51]:
s = np.array([120, 90, 200, 175, 60, 145])
total = np.sum(s)
average = np.average(s)
contributions = np.round((s / total * 100),2)
print(f"Total: {total}")
print(f"Average: {average:.2f}")
print("Percent contributions by month:")
for i, pct in enumerate(contributions, 1):
    print(f" Month {i}: {pct:.2f}%")

Total: 790
Average: 131.67
Percent contributions by month:
 Month 1: 15.19%
 Month 2: 11.39%
 Month 3: 25.32%
 Month 4: 22.15%
 Month 5: 7.59%
 Month 6: 18.35%


## Section B — NumPy: Probability

**B1.** Set `np.random.seed(0)`, then generate 5 random numbers. In a comment, explain why seeding is useful.

In [105]:
# np.random.seed(42)
random_ints = np.random.randint(5,size=5)
print(random_ints)
# Seeding fixes the random generator's starting point, so the same
# "random" numbers are produced on every run — making results
# reproducible and testable/verifiable by others.


[2 3 3 0 2]


**B2.** Generate 5 random integers between 1 and 6 (inclusive) to simulate dice rolls. *(Hint: `high` is exclusive.)*

In [106]:
print(np.random.randint(1, 7, 5))

[5 3 5 1 2]


**B3.** Generate a `(2, 3)` array of random floats between 0 and 1 using `np.random.rand`.

In [115]:
arr = np.random.rand(2, 3) 
print(arr)

[[0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303]]


**B4.** Use `np.random.choice` to pick 10 samples from `['red', 'green', 'blue']`. Then make `red` twice as likely as the others.

In [119]:
sample = ['red', 'green', 'blue']
arr = np.random.choice(sample,10,p=[0.5,0.25,0.25])
print(arr)



['blue' 'blue' 'red' 'red' 'blue' 'green' 'green' 'blue' 'red' 'red']


**B5.** Simulate rolling a die **1000 times**. Estimate P(rolling a 6) and compare it to 1/6.

In [125]:
rolls = np.random.randint(1,7,1000)
p_of_6 = np.mean(rolls == 6)
print(p_of_6, 1/6)

[5 2 6 5 3 4 6 2 5 4 6 4 2 5 4 4 1 4 1 5 6 6 5 5 3 5 4 6 2 6 1 6 3 5 5 6 2
 2 3 1 6 5 6 3 4 4 3 5 3 5 2 3 5 3 3 5 5 1 3 4 3 3 5 3 6 3 6 4 5 3 6 6 6 2
 1 4 3 2 3 3 5 5 5 2 3 1 4 5 5 3 3 2 2 5 3 1 4 3 3 6 2 4 5 3 5 3 5 4 2 4 6
 1 2 4 6 1 6 3 3 5 2 3 6 2 3 5 4 5 1 3 1 1 6 2 6 3 1 4 1 4 6 6 2 1 5 6 6 2
 4 2 1 3 3 4 6 4 6 6 3 4 2 6 5 5 2 5 1 6 2 4 6 2 3 4 3 6 4 5 2 6 1 4 4 6 6
 3 5 3 3 5 1 3 3 4 5 2 1 1 5 6 6 4 4 5 4 1 1 2 6 5 3 6 3 2 2 4 2 2 3 4 2 6
 2 4 5 4 3 5 6 1 4 3 6 5 6 4 2 4 1 4 5 5 4 5 2 6 4 2 6 6 2 3 4 6 6 5 6 2 6
 3 4 4 6 1 1 2 1 2 5 2 1 6 5 1 2 3 4 1 2 5 1 1 4 2 3 5 2 5 1 4 4 6 3 4 1 3
 2 4 3 1 6 5 5 1 1 5 6 3 5 1 4 2 6 6 4 4 1 5 3 6 6 4 5 6 3 4 3 5 6 2 6 5 6
 6 1 6 6 3 2 3 3 4 1 3 5 5 6 4 1 1 6 5 2 4 6 4 5 5 2 2 1 4 4 5 1 6 4 1 1 5
 1 2 2 3 5 6 3 2 3 5 5 1 4 1 5 2 6 2 1 6 5 2 5 6 6 2 5 3 5 6 5 1 3 4 1 4 2
 4 5 4 6 1 1 4 1 6 1 4 3 3 2 1 4 1 5 6 1 1 3 6 4 1 3 2 6 3 3 3 1 1 2 5 5 5
 6 6 2 6 5 5 3 6 1 1 3 3 3 1 5 3 2 3 4 3 1 6 3 6 4 2 6 5 3 4 4 6 2 1 3 4 2
 5 4 2 1 1 4 4 6 3 2 4 3 

**B6.** In a comment, explain the difference between `np.random.rand`, `np.random.randn`, and `np.random.randint`. Show one example of each.

In [ ]:
# np.random.rand generates floats from a uniform distribution over [0, 1)
print(np.random.rand(2, 3))

# np.random.randn generates floats from the standard normal distribution (mean 0, std 1)
print(np.random.randn(1))

# np.random.randint generates random integers in [low, high)
print(np.random.randint(1, 6))

[[0.30777091 0.6136379  0.89793529]
 [0.80992442 0.58313022 0.73022172]]
[1.39959465]
5


**B7.** Simulate flipping a fair coin 1000 times (0 = tails, 1 = heads) and report the proportion of heads.

In [ ]:
flips = np.random.randint(0, 2, 1000)
proportion = np.mean(flips == 1)
print(f"Proportion of HEAD: {proportion}")

Proportion of HEAD: 0.499, Total: 499


**B8.** Generate 10,000 samples from a normal distribution with mean 50 and std 5. Report the sample mean and std.

In [192]:
sample = np.random.normal(50, 5, 10000)
print(f"Sample mean: {sample.mean():.2f}")   # ≈ 50
print(f"Sample std : {sample.std():.2f}")    # ≈ 5


Sample mean: 50.06
Sample std : 5.04


**B9.** Roll two dice 100,000 times. Estimate P(sum == 7).

In [193]:
dice_1 = np.random.randint(1,7,100000)
dice_2 = np.random.randint(1,7,100000)
prob = np.mean((dice_1 + dice_2) == 7)
print(f"Problatity of getting sum of both dice equals to 7 is: {prob}")

Problatity of getting sum of both dice equals to 7 is: 0.1671


**B10.** From `np.random.randint(0, 100, 20)`, estimate the probability that a value is greater than 75.

In [194]:
arr = np.random.randint(0, 100, 20)
prob = np.mean(arr > 75)
print(f"The probability that a value is greater than 75: {prob}")


The probability that a value is greater than 75: 0.25


## Section C — Pandas: Series

**C1.** Create a Pandas Series from `[10, 20, 30, 40]` with index labels `['a', 'b', 'c', 'd']`.

In [ ]:
srs = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(srs)

**C2.** Given `s = pd.Series([5, 15, 25], index=['x', 'y', 'z'])`, access the value at label `'y'` and the value at position `0`. *(Hint: `.loc` vs `.iloc`.)*

In [200]:
s = pd.Series([5, 15, 25], index=['x', 'y', 'z'])
print(f"Label Y: {s.loc['y']}")
print(f"Position 0: {s.iloc[0]}")

Label Y: 15
Position 0: 5


**C3.** In a markdown or comment: what is the difference between a Pandas Series and a NumPy 1-D array?

**C4.** Create a Series from `{'Mon': 100, 'Tue': 80, 'Wed': 120}`. What becomes the index?

**C5.** Given `s = pd.Series([3, 8, 1, 9, 4])`, select all values greater than 4 using a boolean condition.

**C6.** For `s = pd.Series([10, 20, 30])`, compute `s * 2` and `s + pd.Series([1, 2, 3])`.

**C7.** Find the `sum`, `mean`, `max`, and `min` of `pd.Series([3, 8, 1, 9, 4])`, then get all descriptive stats at once.

## Section D — Pandas: DataFrame

**D1.** Create a DataFrame from `{'Name': ['Tom', 'Nick', 'Krish'], 'Age': [20, 21, 19]}` and print it.

**D2.** For the DataFrame above, show `df.head()`, `df.tail()`, `df.shape`, and `df.info()`. Note what each returns.

**D3.** From the same `df`, select (a) just the `Age` column, and (b) both `Name` and `Age` columns.

**D4.** Create a small DataFrame, save it with `df.to_csv('sample.csv', index=False)`, read it back with `pd.read_csv`, and show the first 5 rows.

**D5.** Using `df = pd.DataFrame({'Name':['A','B','C'], 'Age':[30, 25, 40]})`, filter all rows where `Age > 26`.

**D6.** Given `df = pd.DataFrame({'Name':['A','B','C'], 'Marks':[45, 80, 50]})`, add a new column `Passed` that is `True` when `Marks >= 50`.

**D7.** For any numeric DataFrame, call `df.describe()` and note which columns it summarizes.

**D8.** Given `df = pd.DataFrame({'Name':['A','B','C'], 'Age':[30, 25, 40]})`, compute the average Age and find the name of the oldest person. *(Hint: `idxmax`.)*

---
**Done?** Check your answers against `practice-test.md` and re-do any you missed from a blank cell. Good luck! 🎯

## Section E — Missed Concepts (from class quiz)

These 6 target the exact questions I missed in the SMIT assessment. Each has a ⚠️ trap note.
Solve in the blank cell below it, then check the **Section E** answer key in `practice-test.md`.

**E1.** *(Missed Q11 — `linspace` vs `random.rand`)* Create an array of **5 evenly spaced** values from 0 to 1. Then create **6 evenly spaced** values from 0 to 100.

⚠️ *“Evenly spaced” → `np.linspace`, never `np.random.rand`.*

**E2.** *(Missed Q21 — 1-D shape)* Predict the shape of `np.array([1, 2, 3])` **before** running, then verify with `.shape`. Next, build a **2-D** array whose shape is `(1, 3)`.

⚠️ *A 1-D array's shape is `(3,)` — a one-element tuple, not `(1, 3)`.*

**E3.** *(Missed Q29 — selecting a column)* Given `df = pd.DataFrame({'Name': ['A', 'B'], 'Age': [30, 25]})`, select the `Age` column in **two** different ways.

⚠️ *There is no `df.column(...)`. Use `df['Age']` (brackets) or `df.Age`.*

**E4.** *(Missed Q31 — sorting)* Sort `df = pd.DataFrame({'Name': ['A', 'B', 'C'], 'Age': [30, 25, 40]})` by `Age`. Bonus: sort it back by its index.

⚠️ *Pandas uses `df.sort_values(by='Age')`, not `sort()`. Index → `df.sort_index()`.*

**E5.** *(Missed Q43 — column dtypes)* For the `df` above, print the **data type of each column**. Then, separately, print just the **column names**.

⚠️ *Types → `df.dtypes` (attribute, no `()`). Names → `df.columns`. Don't mix them.*

**E6.** *(Missed Q50 — removing duplicates)* Given `df = pd.DataFrame({'Name': ['A', 'B', 'A'], 'Age': [30, 25, 30]})`, remove the duplicate **rows**. Then, separately, get the **unique values** of just the `Name` column.

⚠️ *Rows → `df.drop_duplicates()`. Distinct values of one Series → `df['Name'].unique()`.*